{% set version = "0.6" %}

package:
  name: terminado
  version: {{ version }}

source:
  fn: terminado-{{ version }}.tar.gz
  url: https://github.com/takluyver/terminado/archive/0.6.tar.gz
  sha256: 6a1cfe8ede41962827ca8260bc64f387de85be62fd4e936bdde2ecf2a433931c

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python
  run:
    - python
    - ptyprocess
    - tornado >=4

test:
  imports:
    - terminado

  requires:
    - nose

  commands:
    - nosetests terminado

about:
  home: http://github.com/mitsuhiko/markupsafe
  license: BSD 3-clause
  summary: Terminals served by tornado websockets
