{% set version="3.15.0" %}
{% set year="2016" %}
{% set version_split=version.split(".") %}
{% set major=version_split[0] %}
{% set minor=version_split[1]|int * 10 %}
{% set bugfix=version_split[2]|int * 100 %}
{% set version_coded=(major ~ (("%03d" % minor)|string) ~ (("%03d" % bugfix)|string)) %}

package:
  name: sqlite
  version: {{ version }}

source:
  fn: sqlite-autoconf-{{ version_coded }}.tar.gz
  url: https://www.sqlite.org/{{ year }}/sqlite-autoconf-{{ version_coded }}.tar.gz
  sha256: 77162da9b4a0336d7e77d5252b690662850f62b47c12d9125f74ab9de78ded27

build:
  number: 0

test:
  commands:
    - sqlite3 --version

about:
  home: http://www.sqlite.org/
  license: Public-Domain (http://www.sqlite.org/copyright.html)
  license_family: Public-Domain
  summary: 'Implements a self-contained, zero-configuration, SQL database engine.'
