{% set name = "filelock" %}
{% set version = "2.0.7" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
   fn: {{ name }}-{{ version }}.tar.gz
   url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
   sha256: bdff3edefb9d1df7d40ce9b653adfafd4ba7e2105bc8de78c65aa03641f8ee16

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python

  run:
    - python

test:
  imports:
    - filelock

about:
  home: https://github.com/benediktschmitt/py-filelock
  license: Public Domain
  summary: 'A platform independent file lock.'
