{%set name = "jmespath" %}
{%set version = "0.9.1" %}
{%set hash_type = "sha256" %}
{%set hash_val = "e72d02de23c1814322f7c0dcffb46716271f9b52b129aace0ab6f5a0450d5f02" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - {{ name }}


about:
  home: https://github.com/jmespath/jmespath.py
  license: MIT
  summary: 'JSON Matching Expressions'
