{%set name = "jmespath" %}
{%set version = "0.9.2" %}
{%set hash_type = "sha256" %}
{%set hash_val = "54c441e2e08b23f12d7fa7d8e6761768c47c969e6aed10eead57505ba760aee9" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - {{ name }}


about:
  home: https://github.com/jmespath/jmespath.py
  license: MIT
  summary: 'JSON Matching Expressions'
