# Full credit goes to https://github.com/conda/conda-recipes for providing this recipe.
# It has been subsequently adapted for automated building with conda-forge.

{% set version = "2.0.0" %}

package:
  name: matplotlib
  version: {{ version }}

source:
  fn: matplotlib-{{ version }}.tar.gz
  url: https://github.com/matplotlib/matplotlib/archive/v{{ version }}.tar.gz
  sha256: 966a0807bc961726a68e5b60b6e97c91eed6ba20e0d50dfd699a8f854b2d7370

build:
    number: 0

requirements:
  build:
    - python
    - setuptools
    - numpy x.x
    - python-dateutil
    - freetype 2.7.*
    - cycler >=0.10
    - nose
    - pyparsing
    - pytz
    - libpng >=1.6.23,<1.7
    - tk 8.6.*
    - functools32  # [py27]
    - subprocess32 # [py27]
  run:
    - python
    - numpy x.x
    - cycler >=0.10
    - python-dateutil
    - freetype 2.7.*
    - pytz
    - pyparsing
    - libpng >=1.6.23,<1.7
    - tk 8.6.*
    - functools32  # [py2k]
    - subprocess32 # [py27]
    - setuptools

test:
    imports:
        - matplotlib
        - matplotlib.pyplot
        - mpl_toolkits

about:
  home: http://matplotlib.org/
  license: PSF-based (http://matplotlib.org/users/license.html)
  summary: Publication quality figures in Python
