{% set version = "2.6.0" %}

package:
  name: jsonschema
  version: {{ version }}

source:
  fn: jsonschema-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/j/jsonschema/jsonschema-{{ version }}.tar.gz
  md5: 50c6b69a373a8b55ff1e0ec6e78f13f4

build:
  number: 0
  script: pip install .

requirements:
  build:
    - python
    - pip
    - vcversioner
  run:
    - python
    - functools32  # [py27]

test:
  imports:
    - jsonschema

about:
  home: https://github.com/Julian/jsonschema
  license: MIT
  summary: Python implementation of JSON Schema
