{% set version = "0.5.2" %}

package:
  name: pywavelets
  version: {{ version }}

source:
  fn: PyWavelets-{{ version }}.tar.gz
  url: https://github.com/PyWavelets/pywt/archive/v{{ version }}.tar.gz
  sha256: e36d629f40f7781da2dcaa2139bc476e9deaf91d79f675b5ce0bde6e775d1b53

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - cython
    - numpy x.x
    - setuptools
  run:
    - python
    - numpy x.x

test:
  requires:
    - nose

about:
  home: https://github.com/PyWavelets/pywt
  license: MIT
  license_file: COPYING
  summary: 'Discrete Wavelet Transforms in Python.'
