{% set version = "5.2.1" %}

package:
  name: nbconvert
  version: {{ version }}

source:
  fn: nbconvert-{{ version }}.tar.gz
  url: https://github.com/jupyter/nbconvert/archive/{{ version }}.tar.gz
  sha256: b9e37d8d947f498863476337e01cc7ef36193ccaa3079b428298b901a4c5bdaa

build:
  number: 0
  noarch: python
  script: pip install --no-deps .
  entry_points:
    - jupyter-nbconvert = nbconvert.nbconvertapp:main

requirements:
  build:
    - python
    - pip
  run:
    - bleach
    - entrypoints >=0.2.2
    - jinja2
    - jupyter_core
    - mistune >0.6
    - nbformat
    #- pandoc
    - pandocfilters >=1.4.1
    - python
    - pygments
    - testpath
    - traitlets

test:
  imports:
    - nbconvert
    - nbconvert.exporters
    - nbconvert.filters
    - nbconvert.postprocessors
    - nbconvert.preprocessors
    - nbconvert.resources
    - nbconvert.tests
    - nbconvert.utils
    - nbconvert.writers

  commands:
    - jupyter-nbconvert --help

about:
  home: http://jupyter.org
  license: BSD 3-Clause
  summary: 'Converting Jupyter Notebooks'
