{% set name = "decorator" %}
{% set version = "4.1.0" %}
{% set sha256 = "53d6e5864a8f11e38eddf2206ad6de3eb4738114e54c9fb6bbe47a7ddbec523b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - decorator

about:
  home: http://pypi.python.org/pypi/decorator
  license: BSD
  license_file: LICENSE.txt
  summary: Better living through Python with decorators
  description: |
    Preserve the signature of decorated functions in a consistent way
    across Python releases.
  doc_url: http://pythonhosted.org/decorator/
  dev_url: https://github.com/micheles/decorator
