{% set version = "1.4.1" %}

package:
  name: pkginfo
  version: {{ version }}

source:
  fn: pkginfo-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/pkginfo/pkginfo-{{ version }}.tar.gz
  md5: 3d093d5b51c7902e7dd1736100e0ce87

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - pkginfo = pkginfo.commandline:main
  
requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - pkginfo

about:
  home: https://pypi.python.org/pypi/pkginfo/
  license: PSF
  summary: 'Query metadatdata from sdists / bdists / installed packages.'
