{% set name = "conda" %}
{% set version = "4.3.14" %}
{% set checksum = "1b67ad6f7eaa8d3eafa89686d8a832129fb94fc95fc437226d4e257ea063fef6" %}

package:
  name: conda
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/conda/conda/archive/{{ version }}.tar.gz
  sha256: {{ checksum }}

build:
  number: 0
  entry_points:
    - conda = conda.cli:main
    - conda-env = conda_env.cli.main:main
  always_include_files:
    - bin/conda
    - bin/activate
    - bin/deactivate

requirements:
  build:
    - python
  run:
    - python
    - conda-env >=2.6
    - enum34                 # [py<34]
    - pycosat >=0.6.1
    - requests >=2.12.4
    - ruamel_yaml >=0.11.14
    - pyopenssl >=16.2

test:
  imports:
    - conda
  commands:
    - which conda
    - which conda-env
    - conda --version
    - conda info
    - conda env --help

about:
  home: https://github.com/conda/conda
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: OS-agnostic, system-level binary package manager.
  description: |
    Conda is an open source package management system and environment
    management system for installing multiple versions of software packages
    and their dependencies and switching easily between them. It works on
    Linux, OS X and Windows, and was created for Python programs but can
    package and distribute any software.
  doc_url: http://conda.pydata.org/docs/
  dev_url: https://github.com/conda/conda
