{% set version = "0.7.4" %}

package:
  name: mistune
  version: {{ version }}

source:
  fn: mistune-{{ version }}.tar.gz
  url: https://github.com/lepture/mistune/archive/v{{ version }}.tar.gz
  sha256: 5030d5e3e0ec90fbdaed0f52d3c756ffb30e4ab46c3de159c97482c09569abcb

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - mistune

about:
  home: https://github.com/lepture/mistune
  license:  BSD 3-clause
  summary: The fastest markdown parser in pure Python
