{% set version = "0.19.1" %}

package:
  name: scipy
  version: {{ version }}

source:
  fn: scipy-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/s/scipy/scipy-{{ version }}.tar.gz
  sha256: a19a2ca7a7336495ec180adeaa0dfdcf41e96dbbee90d51c3ed828ba570884e6

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - cython
    - libgfortran
    - openblas 0.2.19
    - numpy x.x
  run:
    - python
    - libgfortran
    - openblas 0.2.19
    - numpy x.x

test:
  requires:
    - nose

about:
  home: http://www.scipy.org/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: Scientific Library for Python
  description: |
    SciPy is a Python-based ecosystem of open-source software for mathematics,
    science, and engineering.
  doc_url: http://www.scipy.org/docs.html
  dev_url: https://github.com/scipy/scipy
