{% set version = "0.19.0" %}

package:
  name: scipy
  version: {{ version }}

source:
  fn: scipy-{{ version }}.zip
  url: https://pypi.io/packages/source/s/scipy/scipy-{{ version }}.zip
  sha256: 4190d34bf9a09626cd42100bbb12e3d96b2daf1a8a3244e991263eb693732122

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - cython
    - libgfortran
    - openblas 0.2.19
    - numpy x.x
  run:
    - python
    - libgfortran
    - openblas 0.2.19
    - numpy x.x

test:
  requires:
    - nose

about:
  home: http://www.scipy.org/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: Scientific Library for Python
  description: |
    SciPy is a Python-based ecosystem of open-source software for mathematics,
    science, and engineering.
  doc_url: http://www.scipy.org/docs.html
  dev_url: https://github.com/scipy/scipy
