{% set name = "idna" %}
{% set version = "2.2" %}
{% set hash_type = "sha256" %}
{% set hash = "0ac27740937d86850010e035c6a10a564158a5accddf1aa24df89b0309252426" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - idna

about:
  home: https://github.com/kjd/idna
  license: BSD Like
  license_file: LICENSE.rst
  summary: Internationalized Domain Names in Applications (IDNA).
  description: |
    A library to support the Internationalised Domain Names in Applications
    (IDNA) protocol as specified in RFC 5891. This version of the protocol
    is often referred to as “IDNA2008”.
