{% set name = "scikit-learn" %}
{% set version = "0.18.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1eddfc27bb37597a5d514de1299981758e660e0af56981c0bfdf462c9568a60c

build:
  number: 0

requirements:
  build:
    - cython
    - python
    - setuptools
    - openblas 0.2.19|0.2.19.*
    - numpy x.x
    - scipy
    - nose

  run:
    - python
    - openblas 0.2.19|0.2.19.*
    - numpy x.x
    - scipy

test:
  requires:
    - nose

  imports:
    - sklearn

  commands:
    - nosetests sklearn --exe

about:
  home: http://scikit-learn.org/
  license: BSD 3-Clause
  summary: A set of python modules for machine learning and data mining
