{% set version = "4.4.1.1" %}

package:
  name: libnetcdf
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/Unidata/netcdf-c/archive/v{{ version }}.tar.gz
  sha256: 7f040a0542ed3f6d27f3002b074e509614e18d6c515b2005d1537fec01b24909

build:
  number: 0

requirements:
  build:
    - curl
    - zlib 1.2.*
    - hdf5 1.8.17|1.8.17.*
  run:
    - curl
    - zlib 1.2.*
    - hdf5 1.8.17|1.8.17.*

test:
  commands:
    - nc-config --all
    - test -f ${PREFIX}/lib/libnetcdf.a
    - test -f ${PREFIX}/lib/libnetcdf.so

about:
  home: http://www.unidata.ucar.edu/software/netcdf/
  license: MIT
  summary: 'Libraries and data formats that support array-oriented scientific data.'
