{% set name = "numpy" %}
{% set version = "1.13.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.zip
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: c9b0283776085cb2804efff73e9955ca279ba4edafd58d3ead70b61d209c4fbb

build:
  number: 0

requirements:
  build:
    - cython
    - python
    - setuptools
    - openblas 0.2.19
  run:
    - python
    - openblas 0.2.19

test:
  requires:
    - nose
  commands:
    - f2py -h
  imports:
    - numpy
    - numpy.linalg.lapack_lite

about:
  home: http://numpy.scipy.org/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: array processing for numbers, strings, records, and objects.
