{% set pkg_name = "appdirs" %}
{% set version = "1.4.3" %}
{% set sha256 = "9e5896d1372858f8dd3344faf4e5014d21849c756c8d5701f78f8a103b372d92" %}

package:
  name: {{ pkg_name }}
  version: {{ version }}

source:
  fn: {{ pkg_name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ pkg_name[0] }}/{{ pkg_name }}/{{ pkg_name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
    number: 0
    script: python setup.py install

requirements:
    build:
        - python
    run:
        - python

test:
    imports:
        - appdirs

about:
    home: http://github.com/ActiveState/appdirs
    license: MIT License
    summary: A small Python module for determining appropriate platform-specific dirs
