{% set version = "0.2.3" %}

package:
    name: entrypoints
    version: {{ version }}

source:
    fn: {{ version }}.tar.gz
    url: https://github.com/takluyver/entrypoints/archive/{{ version }}.tar.gz
    md5: ad31adbe634709555c400de125098dc8

build:
    number: 0

requirements:
    build:
        - python
    run:
        - python
        - configparser  # [py<35]

test:
    imports:
        - entrypoints

about:
    home: http://entrypoints.readthedocs.org/en/latest/
    license: MIT
    summary: Discover and load entry points from installed packages
