{% set version = "5.1.3" %}

package:
  name: psutil
  version: {{ version }}

source:
  fn: psutil-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/psutil/psutil-{{ version }}.tar.gz
  md5: 3090e32d42761086ae82036cadb95ba3

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  requires:
    - ipaddress    # [py<33]
    - mock         # [py<33]
    - unittest2    # [py<27]

  imports:
    - psutil
    - psutil.tests

about:
  home: https://github.com/giampaolo/psutil
  license: BSD 3-Clause
  summary: A cross-platform process and system utilities module for Python
