{% set version = "4.1.5" %}
{% set ver_maj_min_str = "-".join(version.split(".")[:2]) %}

package:
  name: zeromq
  version: {{ version }}

source:
  fn: zeromq-{{ version }}.tar.gz
  url: https://github.com/zeromq/zeromq{{ ver_maj_min_str }}/releases/download/v{{ version }}/zeromq-{{ version }}.tar.gz
  sha1: 2b7490b77860be3060b1b1f92cd73184d309ca69
  patches:
    # Patch to avoid a failing test on Linux. See issue for details.
    # https://github.com/zeromq/libzmq/issues/1462
    - Makefile.am.linux.patch  # [linux]

build:
  number: 0

requirements:
  build:
    - libsodium

  run:
    - libsodium

test:
  commands:
    - test -f ${PREFIX}/lib/libzmq.a
    - test -f ${PREFIX}/lib/libzmq.so

about:
  home: http://zeromq.org
  license: LGPL 3
  summary: A high-performance asynchronous messaging library.
