package:
  name: tblib
  version: 1.3.0

source:
  fn: tblib-1.3.0.tar.gz
  url: https://pypi.python.org/packages/source/t/tblib/tblib-1.3.0.tar.gz
  md5: 0dbc13ffc624aa1603ab125404fa7b7d

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - tblib

about:
  home: https://github.com/ionelmc/python-tblib
  license: BSD
  license_file: LICENSE
  summary: Traceback fiddling library for Python
  description: |
    A traceback serialization library allowing you to Pickle tracebacks and
    raise exceptions with pickled tracebacks in different processes. This
    allows better error handling when running code over multiple processes.
  doc_url: https://readthedocs.org/projects/python-tblib/
  dev_url: https://github.com/ionelmc/python-tblib
