{% set name = "tblib" %}
{% set version = "1.3.1" %}
{% set hash = "180372043269a714ea5d6b86461da07b62fce68f93d02a6276bec5e9ad531caf" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - tblib

about:
  home: https://github.com/ionelmc/python-tblib
  license: BSD
  license_file: LICENSE
  summary: Traceback fiddling library for Python
  description: |
    A traceback serialization library allowing you to Pickle tracebacks and
    raise exceptions with pickled tracebacks in different processes. This
    allows better error handling when running code over multiple processes.
  doc_url: https://readthedocs.org/projects/python-tblib/
  dev_url: https://github.com/ionelmc/python-tblib
