package:
  name: sqlalchemy
  version: 1.1.4

source:
  fn: SQLAlchemy-1.1.4.tar.gz
  url: https://pypi.python.org/packages/ca/ca/c2436fdb7bb75d772d9fa17ba60c4cfded6284eed053a7274b2beb96596a/SQLAlchemy-1.1.4.tar.gz
  md5: be5af1bebe595206b71b513a14836e4f

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - sqlalchemy
    - sqlalchemy.cprocessors
    - sqlalchemy.cresultproxy
    - sqlalchemy.cutils

about:
  home: http://www.sqlalchemy.org/
  license: MIT
  license_file: LICENSE
  summary: Database Abstraction Library
  description: |
    SQLAlchemy is the Python SQL toolkit and Object Relational Mapper that
    gives application developers the full power and flexibility of SQL.
  doc_url: http://docs.sqlalchemy.org/en/rel_1_0/
  dev_url: https://bitbucket.org/zzzeek/sqlalchemy/
