{% set version = "0.2.0" %}

package:
  name: ipython_genutils
  version: {{ version }}

source:
  fn: ipython_genutils-{{ version }}.tar.gz
  url: https://github.com/ipython/ipython_genutils/archive/{{ version }}.tar.gz
  md5: 477e596a0e6e2f74ec08ec09687eeb6c

build:
  number: 0
  noarch: python
  script: python setup.py install

requirements:
  build:
    - python
  run:
    - python

test:
  imports:
    - ipython_genutils
    - ipython_genutils.testing
    - ipython_genutils.tests

about:
  home: http://ipython.org
  license: BSD 3-Clause
  summary: Vestigial utilities from IPython
