{%set name = "pathlib2" %}
{%set version = "2.2.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: c2e73a9a560e8b86233923af6a37faa2

requirements:
  build:
    - python
    - setuptools
    - six
  run:
    - python
    - six
    - scandir  # [py<35]

test:
  imports:
    - pathlib2

about:
  home: https://pypi.python.org/pypi/pathlib2/
  license: MIT
  summary: object-oriented filesystem paths
