{% set name = "pathlib2" %}
{% set version = "2.3.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: 89c90409d11fd5947966b6a30a47d18c

requirements:
  build:
    - python
    - setuptools
    - six
  run:
    - python
    - six
    - scandir  # [py<35]

test:
  imports:
    - pathlib2

about:
  home: https://pypi.python.org/pypi/pathlib2/
  license: MIT
  summary: object-oriented filesystem paths
