package:
  name: python
  version: 3.5.2

source:
  fn: Python-3.5.2.tgz
  url: https://www.python.org/ftp/python/3.5.2/Python-3.5.2.tgz
  sha256: 1524b840e42cf3b909e8f8df67c1724012c7dc7f9d076d4feef2d3eff031e8a0

build:
  number: 1
  no_link:
    - bin/python3.5
  script_env:
    - python_branding
  skip_compile_pyc:
    - lib/python3.5/test/*bad*.py
    - lib/python3.5/lib2to3/tests/data/*.py
  ignore_prefix_files:
    - lib/libpython3.5m.so.1.0
    - lib/python3.5/lib-dynload/*.so

requirements:
  build:
    - bzip2 1.0.*
    - openssl 1.0.*
    - readline 6.3*
    - sqlite 3.15.*
    - tk 8.6.*
    - xz 5.2.*
    - zlib 1.2.*
  run:
    - openssl 1.0.*
    - readline 6.3*
    - sqlite 3.15.*
    - tk 8.6.*
    - xz 5.2.*
    - zlib 1.2.*

test:
  commands:
    - python -V
    - python3 -V
    - 2to3 -h
    - pydoc -h
    - python3-config --help

about:
  home: http://www.python.org/
  license: PSF
  summary: General purpose programming language
