{% set name = "pbr" %}
{% set version = "3.0.0" %}
{% set sha256 = "568f988af109114fbfa0525dcb6836b069838360d11732736ecc82e4c15d5c12" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  preserve_egg_dir: True
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - pbr = pbr.cmd.main:main

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - pip

test:
  imports:
    - pbr
    - pbr.cmd
    - pbr.hooks

  commands:
    - pbr --help

about:
  home: https://launchpad.net/pbr
  license: Apache 2.0
  summary: Python Build Reasonableness
