{% set version = "0.7.4" %}

package:
  name: pickleshare
  version: {{ version }}

source:
  fn: pickleshare-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/pickleshare/pickleshare-{{ version }}.tar.gz
  md5: 6a9e5dd8dfc023031f6b7b3f824cab12

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - pathlib2  # [py<34]

test:
  imports:
    - pickleshare

about:
  home: https://github.com/vivainio/pickleshare
  license: MIT
  summary: "Tiny 'shelve'-like database with concurrency support"
