{% set version = "0.5.2" %}

package:
  name: ptyprocess
  version: {{ version }}

source:
  fn: ptyprocess-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/ptyprocess/ptyprocess-{{ version }}.tar.gz
  md5: d3b8febae1b8c53b054bd818d0bb8665

build:
  noarch: python
  number: 0

requirements:
  build:
    - python
  run:
    - python

test:
  imports:
    - ptyprocess

about:
  home: https://github.com/pexpect/ptyprocess
  license: ISC
  summary: 'Run a subprocess in a pseudo terminal'
