{% set name = "pytest" %}
{% set version = "3.1.3" %}
{% set sha256 = "095e1832f7e424563c95daf4d8d3c865052b80e139cdd2f9610a986ee8526206" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - py.test = py.test:main

requirements:
  build:
    - python
    - py
    - setuptools
    - setuptools_scm
  run:
    - python
    - setuptools
    - py >=1.4.29

test:
  commands:
    - py.test -h
  imports:
    - pytest

about:
  home: http://pytest.org/
  license: MIT
  license_file: LICENSE
  summary: 'Simple and powerful testing with Python.'
  description: |
    The pytest framework makes it easy to write small tests, yet scales to
    support complex functional testing for applications and libraries.
  doc_url: http://pytest.org/latest/contents.html
  dev_url: https://github.com/pytest-dev/pytest/
