{% set version = "4.0.6" %}

package:
  name: libtiff
  version: {{ version }}

source:
  fn: tiff-{{ version }}.tar.gz
  url: http://download.osgeo.org/libtiff/tiff-4.0.6.tar.gz
  sha256: 4d57a50907b510e3049a4bba0d7888930fdfc16ce49f1bf693e5b6247370d68c

build:
  number: 0

requirements:
  build:
    - zlib 1.2.*
    - jpeg 9*
    - xz 5.2.*
  run:
    - zlib 1.2.*
    - jpeg 9*
    - xz 5.2.*

test:
  commands:
    - test -f ${PREFIX}/lib/libtiff.a
    - test -f ${PREFIX}/lib/libtiffxx.a
    - test -f ${PREFIX}/lib/libtiff.so
    - test -f ${PREFIX}/lib/libtiffxx.so

about:
  home: http://www.remotesensing.org/libtiff/
  license: HPND
  summary: 'Support for the Tag Image File Format (TIFF).'
