{% set name = "beautifulsoup4" %}
{% set version = "4.5.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: 937e0df0d699a1237646f38fd567f0c6

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - bs4

about:
  home: http://www.crummy.com/software/BeautifulSoup/
  license: MIT
  license_file: COPYING.txt
  summary: Python library designed for screen-scraping
  description: |
    Beautiful Soup is a library for pulling data out of HTML and XML files.
    It provides ways of navigating, searching, and modifying parse trees.
  doc_url: http://www.crummy.com/software/BeautifulSoup/bs4/doc/
  dev_url: https://code.launchpad.net/beautifulsoup
