{% set name = "pandas" %}
{% set version = "0.20.1" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    fn: {{ name }}-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 42707365577ef69f7c9c168ddcf045df2957595a9ee71bc13c7997eecb96b190

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
    build:
        - python
        - setuptools
        - cython
        - numpy  x.x
    run:
        - python
        - numpy  x.x
        - python-dateutil
        - pytz

test:
    imports:
        - pandas

about:
    home: http://pandas.pydata.org
    license: BSD 3-clause
    summary: high-performance, easy-to-use data structures and data analysis tools.
