{% set name = "testpath" %}
{% set version = "0.3.1" %}
{% set wheel_tag = "py2.py3-none-any" %}
{% set fn = "{}-{}-{}.whl".format(name, version, wheel_tag) %}
{% set sha256 = "039fa6a6c9fd3488f8336d23aebbfead5fa602c4a47d49d83845f55a595ec1b4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ fn }}
  url: https://pypi.io/packages/py2.py3/{{ name[0] }}/{{ name }}/{{ fn }}
  sha256: {{ sha256 }}

build:
  number: 0
  script: pip install --no-deps {{ fn }}

requirements:
  build:
    - python
    - pip
  run:
    - python
    - pathlib2  # [py2k]

test:
  imports:
    - testpath

about:
  home: https://testpath.readthedocs.io
  license: MIT
  license_family: MIT
  summary: Testpath is a collection of utilities for Python code working with files and commands.
  description: |
    Testpath contains functions to check things on the filesystem,
    and tools for mocking system commands and recording calls to those.
  doc_url: https://testpath.readthedocs.io
  dev_url: https://github.com/jupyter/testpath
